### ISSUE TITLE
sites may misreported as suboptimal "A" records when they use our DNS with optimal A records

### ISSUE THREAD

**Issue by fool** [netlify/speedy#25]
e.g. https://testmysite.io/5b622ed71f12b7716e7ef32d/www.cultivateautomation.com

Not a big deal, but not a good sales pitch for our own DNS hosting either :)

**Comment by fool** [comment]
second report on 9 Aug

**Comment by brycekahle** [comment]
It looks like this bug happens when only one speedy server is working. I re-ran this particular site, and it doesn't give the warning anymore. This makes sense, because the check is if all servers get the same IP address. If there is only one server, then of course it will match. 

I would file a bug on https://github.com/netlify/netlify-speedtest to not show this warning if only one server returns results.
